language: python
python:
    - '2.7'
    - '3.5'
install:
    - pip install -r requirements.txt
    - pip install coverage
    - git clone https://github.com/google/macops
    - cd macops/gmacpyutil ; python setup.py install; cd ../..
script:
    - export BOTO_CONFIG=/dev/null
    - coverage run run_tests.py
after_success:
    - curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh
